### ISSUE TITLE
Obelisk with scythe

### ISSUE THREAD

**Issue by Maurits825** [Maurits825/osrs-damage-sim#87]
Obelisk using scythe causes an internal error
<details>
<summary>Setup string</summary>
eyJnbG9iYWxTZXR0aW5ncyI6eyJucGMiOnsibmFtZSI6Ik9iZWxpc2siLCJoaXRwb2ludHMiOjI2MCwiYXR0IjoyMDAsInN0ciI6MTUwLCJkZWYiOjEwMCwibWFnZSI6MTAwLCJyYW5nZSI6MTAwLCJkc3RhYiI6NzAsImRzbGFzaCI6NzAsImRjcnVzaCI6NzAsImRtYWdpYyI6NTAsImRyYW5nZSI6NjAsImlkIjoiMTE3NTEifSwiaXRlcmF0aW9ucyI6MTAwMCwidGVhbVNpemUiOjEsInJhaWRMZXZlbCI6MCwicGF0aExldmVsIjowLCJpc0RldGFpbGVkUnVuIjpmYWxzZX0sImlucHV0R2VhclNldHVwcyI6W3siZ2VhclNldHVwU2V0dGluZ3MiOnsic3RhdERyYWlucyI6W10sImJvb3N0cyI6W10sImNvbWJhdFN0YXRzIjp7ImF0dGFjayI6OTksInN0cmVuZ3RoIjo5OSwicmFuZ2VkIjo5OSwibWFnaWMiOjk5LCJoaXRwb2ludHMiOjk5fX0sIm1haW5HZWFyU2V0dXAiOnsic2V0dXBOYW1lIjoiTWF4IFNjeXRoZSIsInByZXNldE5hbWUiOiJNYXggU2N5dGhlIiwiZ2VhciI6eyIwIjp7ImlkIjoyNjM4Mn0sIjEiOnsiaWQiOjIxMjg1fSwiMiI6eyJpZCI6MTk1NTN9LCIzIjp7ImlkIjoyMjMyNX0sIjQiOnsiaWQiOjI2Mzg0fSwiNSI6bnVsbCwiNyI6eyJpZCI6MjYzODZ9LCI5Ijp7ImlkIjoyMjk4MX0sIjEwIjp7ImlkIjoxMzIzOX0sIjEyIjp7ImlkIjoxMTc3M30sIjEzIjp7ImlkIjoyMjk0N319LCJibG93cGlwZURhcnRzIjp7ImlkIjoxMTIzMH0sImF0dGFja1N0eWxlIjoiQ2hvcCAoU2xhc2gvQWdncmVzc2l2ZSkiLCJzcGVsbCI6bnVsbCwiaXNTcGVjaWFsIjpmYWxzZSwicHJheWVycyI6WyJwaWV0eSJdLCJjb25kaXRpb25zIjpbXSwic3RhdERyYWluIjpbXSwiaXNPblNsYXllclRhc2siOnRydWUsImlzSW5XaWxkZXJuZXNzIjp0cnVlLCJjdXJyZW50SHAiOjEsIm1pbmluZ0x2bCI6OTksImlzS2FuZGFyaW5EaWFyeSI6dHJ1ZX0sImZpbGxHZWFyU2V0dXBzIjpbXX1dfQ==
</details>

**Comment by Maurits825** [comment]
Traceback from logs
```python-traceback
[ERROR]	2023-07-07T09:46:37.370Z	5574e847-ca36-4f4c-bec8-0d17e6b9cc6c	Exception on /run-damage-sim [POST]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/task/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/task/damage_sim/damage_sim_server.py", line 34, in run_damage_sim
    damage_sim_results = damage_sim_runner.run(input_setup)
  File "/var/task/damage_sim/damage_sim_runner.py", line 30, in run
    sim_data, gear_setup_dps_stats, total_tick_data = DamageSimRunner.run_single_gear_setup(
  File "/var/task/damage_sim/damage_sim_runner.py", line 67, in run_single_gear_setup
    dmg_sim_data, tick_data = damage_sim.run()
  File "/var/task/damage_sim/damage_sim.py", line 90, in run
    hitsplat = self.current_weapon.roll_damage()
  File "/var/task/weapons/custom_weapons/scythe.py", line 21, in roll_damage
    self.roll_single_hit(0)
  File "/var/task/weapons/custom_weapons/scythe.py", line 41, in roll_single_hit
    self.hitsplat.hitsplats[hit_count] = damage
IndexError: list assignment index out of range
```

**Comment by Maurits825** [comment]
obelisk npc was not set in wiki (it is now). will be fixed when the wiki scraper is fixed and npcs json is updated
